### ISSUE TITLE
envvars not being used

### ISSUE THREAD

**Issue by ajs6f** [ckan/ckan-docker#107]
I'm trying to adjust the value of `ckan.request.timeout` and `ckan.site_url` from my `.env` file, thusly:
```
...
CKAN__REQUESTS__TIMEOUT=100
...
CKAN_SITE_URL=https://dt-vmckantest.si.edu:8443
```
but the values are ignored:
```
7ffd62e82f2d:/srv/app# grep site_url ckan.ini 
ckan.site_url = http://127.0.0.1:5000
7ffd62e82f2d:/srv/app# grep requests.timeout ckan.ini 
ckan.requests.timeout = 5
```

I've been careful that the containers are completely rebuilt (starting with pulling fresh images, recreating volumes, etc.) via:
```
sudo docker stop $(sudo docker ps -q); sudo docker rm $(sudo docker ps -aq); sudo docker image rm $(sudo docker image ls -q); sudo docker network rm $(sudo docker network ls -q); sudo docker volume rm $(sudo docker volume ls -q) ; sudo docker system prune --all --force
```
and 
```
docker compose up --build --detach --force-recreate
```
with no effect at all. Am I missing something? Is this not the correct mapping to use for the names of the env vars? Is there some special action I need to take to make this take effect? The values are visible to `docker compose`:
```
➜  ckan-docker git:(master) ✗ docker compose config | grep SITE_URL
      CKAN_SITE_URL: https://dt-vmckantest.si.edu:8443
➜  ckan-docker git:(master) ✗ docker compose config | grep REQUEST 
      CKAN__REQUESTS__TIMEOUT: "100"
```

**Comment by themowski** [comment]
1) Is `envvars` the last plugin in the list of plugins? This is required: https://github.com/okfn/ckanext-envvars#requirements

2) Did you verify that the values you are setting are actually being ignored by CKAN, or are you just checking the `ckan.ini` file? I think the point of the `envvars` plugin is that if you define an environment variable with a specific name, then that value will be used **instead of** the value of the corresponding config in the CKAN config file. I don't think the extension updates the `ckan.ini` file in-place, rather, the extension allows you to override the `ckan.ini` file (or to specify things that you explicitly omit from the `ckan.ini` file).

**Comment by ajs6f** [comment]
Sorry to have left this for so long! Quick answers:

1. Yes, it is the last plugin.
2. Yes, the values were ignored, because actual behavior in the app showed the use of default values instead of my proffered values.

This having been said, I was trying to inject special values because I was having problems getting the Docker setup to operate correctly. The problems were ultimately due to networking oddities between the Compose setup and my platform. I straightened out those problems and was able to run (and am currently running a demo arrangement) with the default values. Since

1. my problem isn't relevant to local work any more and
2. in order to try to replicate the problem reported here I would have to intentionally jank our demonstrator and
3. it doesn't seem that anyone else has seen this problem

I will close this issue and if similar behavior arises in the future I will either reopen or report afresh. Thanks for the response and I apologize again for the delay!

**Comment by ajs6f** [comment]
d
