### ISSUE TITLE
Move to Docker Compose

### ISSUE THREAD

**Issue by clementmouchet** [ckan/ckan-docker#13]
Fig has been replaced by Docker Compose, and is now deprecated. 

Service definitions should be compatible already, but the doc has to be updated.

TODO:
* test the definition work with compose
* amend or fix if required
* update the docs

https://docs.docker.com/compose/

**Comment by Analect** [comment]
@clementmouchet 
I renamed fig.yml to docker-compose.yml ... and all appeared to work OK ... until these snags with postgres and nginx ... I'm wondering if you have any thoughts on what might be going wrong here.  I followed the various steps for prepping the ckan-docker folder ahead of running 'docker-compose up'.
Thanks for your efforts with this ... docker makes setting up CKAN so much more manageable.

postgres_1   | ALTER TABLE
postgres_1   | ALTER TABLE
postgres_1   | CREATE ROLE
postgres_1   | ERROR:  relation "user" does not exist at character 465
postgres_1   | STATEMENT:  SELECT "user".password AS user_password, "user".id AS user_id, "user".name AS user_name, "user".openid AS user_openid, "user".fullname AS user_fullname, "user".email AS user_email, "user".apikey AS user_apikey, "user".created AS user_created, "user".reset_key AS user_reset_key, "user".about AS user_about, "user".activity_streams_email_notifications AS user_activity_streams_email_notifications, "user".sysadmin AS user_sysadmin, "user".state AS user_state 
postgres_1   | 	FROM "user" 
postgres_1   | 	WHERE "user".name = 'default' OR "user".openid = 'default' OR "user".id = 'default' ORDER BY "user".name 
postgres_1   | 	 LIMIT 1
nginx_1      | 2015/03/08 05:10:17 [emerg] 1#0: host not found in upstream "ckan" in /etc/nginx/nginx.conf:42
nginx_1      | nginx: [emerg] host not found in upstream "ckan" in /etc/nginx/nginx.conf:42
ckandocker_nginx_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping ckandocker_postgres_1...
Stopping ckandocker_data_1...
Stopping ckandocker_solr_1...
Stopping ckandocker_datapusher_1...

It appears the five other containers set up OK .. but the failure of the nginx one appears to have instigated a graceful shutdown of all the others. Is that expected behaviour?
ubuntu-1404:~/Development/Tools/Eolas/ckan-docker$ docker ps -a
CONTAINER ID        IMAGE                                  COMMAND                CREATED             STATUS                       PORTS                                                            NAMES
b939053a579d        ckandocker_nginx:latest                "nginx -g 'daemon of   3 minutes ago       Exited (1) 3 minutes ago                                                                      ckandocker_nginx_1        
1f86e2fd5ba2        ckandocker_ckan:latest                 "/sbin/my_init --ena   6 minutes ago       Exited (1) 5 minutes ago                                                                      ckandocker_ckan_1         
19885492e734        ckandocker_postgres:latest             "/sbin/my_init"        9 minutes ago       Exited (0) 3 minutes ago                                                                      ckandocker_postgres_1     
e6595b27a572        ckandocker_data:latest                 "/sbin/my_init"        11 minutes ago      Exited (0) 3 minutes ago                                                                      ckandocker_data_1         
6522c731c142        ckandocker_solr:latest                 "/sbin/my_init"        11 minutes ago      Exited (0) 3 minutes ago                                                                      ckandocker_solr_1         
c23c66f68270        ckandocker_datapusher:latest           "python datapusher/m   16 minutes ago      Exited (137) 3 minutes ago                                                                    ckandocker_datapusher_1   

These are the logs from the nginx container:
ubuntu-1404:~/Development/Tools/Eolas/ckan-docker$ docker logs ckandocker_nginx_1 
2015/03/08 05:10:17 [emerg] 1#0: host not found in upstream "ckan" in /etc/nginx/nginx.conf:42
nginx: [emerg] host not found in upstream "ckan" in /etc/nginx/nginx.conf:42

**Comment by clementmouchet** [comment]
Strange, there should be an entry in the hosts file to map "ckan" to it's Docker ip.
I'll have a look at that asap.

**Comment by Analect** [comment]
@clementmouchet 
I took the fig.yml file as per the repo ... and didn't modify it .. other than to rename it docker-compose.yml
What I don't fully understand is that by running that *.yml with docker-compose up, the various containers that got created (visible below from this docker ps -a), have a naming convention that differs from what is described in the links in the yml file ... so names such as ckandocker_ckan_1, ckandocker_postgres_1 etc.. where are these container names coming from? (a simple in-repo search via github doesn't render anything) and should the yml be updated to reflect this naming convention ... so a link such as ckandocker_ckan_1:ckan? ... ie aliasing ckandocker_ckan_1 as ckan.

Thanks,
Colum

CONTAINER ID        IMAGE                                  COMMAND                CREATED             STATUS                      PORTS                                                            NAMES
b939053a579d        ckandocker_nginx:latest                "nginx -g 'daemon of   36 hours ago        Exited (1) 36 hours ago                                                                      ckandocker_nginx_1        
1f86e2fd5ba2        ckandocker_ckan:latest                 "/sbin/my_init --ena   36 hours ago        Exited (1) 36 hours ago                                                                      ckandocker_ckan_1         
19885492e734        ckandocker_postgres:latest             "/sbin/my_init"        36 hours ago        Exited (0) 36 hours ago                                                                      ckandocker_postgres_1     
e6595b27a572        ckandocker_data:latest                 "/sbin/my_init"        36 hours ago        Exited (0) 36 hours ago                                                                      ckandocker_data_1         
6522c731c142        ckandocker_solr:latest                 "/sbin/my_init"        36 hours ago        Exited (0) 36 hours ago                                                                      ckandocker_solr_1         
c23c66f68270        ckandocker_datapusher:latest           "python datapusher/m   36 hours ago        Exited (137) 36 hours ago                                                                    ckandocker_datapusher_1

**Comment by Analect** [comment]
@clementmouchet 
Played around with this a bit more.
After another 'docker-compose up', it appeared to overcome the previous problem ... but complained about not being able to find the pdf_preview plugin (has this been removed from core CKAN .. and does it now need special treatment in this set-up).

Anyway, by removing the reference to pdf_preview in the custom_options.ini, it appeared to work, although I don't know if by design or not, but it doesn't start CKAN in the background ... rather the terminal tails what are presumably the ckan logs, as per below.

ckan_1       | Initialising DB: SUCCESS
ckan_1       | *** Running /etc/rc.local...
ckan_1       | *** Booting runit daemon...
ckan_1       | *** Runit started as PID 52
ckan_1       | /usr/lib/python2.7/dist-packages/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
ckan_1       |   'Supervisord is running as root and it is searching '
ckan_1       | 2015-03-11 15:36:57,754 CRIT Supervisor running as root (no user in config file)
ckan_1       | 2015-03-11 15:36:57,754 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
ckan_1       | 2015-03-11 15:36:57,773 INFO RPC interface 'supervisor' initialized
ckan_1       | 2015-03-11 15:36:57,774 CRIT Server 'unix_http_server' running without any HTTP authentication checking
ckan_1       | 2015-03-11 15:36:57,774 INFO supervisord started with pid 56
ckan_1       | 2015-03-11 15:36:58,776 INFO spawned: 'master' with pid 65
ckan_1       | 2015-03-11 15:36:58,778 INFO spawned: 'apache2' with pid 66
ckan_1       | 2015-03-11 15:36:58,850 INFO success: master entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
ckan_1       | 2015-03-11 15:36:58,951 INFO exited: master (exit status 0; expected)
ckan_1       | 2015-03-11 15:36:59,953 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
solr_1       | 119050 [qtp1711548761-15] INFO  org.apache.solr.core.SolrCore  ? [ckan] webapp=/solr path=/select params={fl=*,score&q=*:*&wt=standard&version=2.2&rows=1} hits=0 status=0 QTime=1 
solr_1       | 119054 [qtp1711548761-16] INFO  org.apache.solr.core.SolrCore  ? [ckan] webapp=/solr path=/admin/file/ params={file=schema.xml} status=0 QTime=1 
solr_1       | 119329 [qtp1711548761-17] INFO  org.apache.solr.core.SolrCore  ? [ckan] webapp=/solr path=/select params={fl=*,score&q=*:*&wt=standard&version=2.2&rows=1} hits=0 status=0 QTime=1 
solr_1       | 119331 [qtp1711548761-18] INFO  org.apache.solr.core.SolrCore  ? [ckan] webapp=/solr path=/admin/file/ params={file=schema.xml} status=0 QTime=0 
solr_1       | 119531 [qtp1711548761-19] INFO  org.apache.solr.core.SolrCore  ? UnInverted multi-valued field {field=groups,memSize=4288,tindexSize=0,time=0,phase1=0,nTerms=0,bigTerms=0,termInstances=0,uses=0}

**Comment by clementmouchet** [comment]
I've tested it at work on a stack of 10 containers based on this project and other services. Looks like an easy upgrade, everything works the same.
Not sure why you had the issue in the first place, I can't reproduce it.

To start the solution as a daemon, you nee to use the -d flag. `docker-compose up -d`

**Comment by clementmouchet** [comment]
merged https://github.com/ckan/ckan-docker/pull/18
